// <auto-generated />
namespace WR.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Rename_SiteSettings_to_BlogSettings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_SiteSettings_to_BlogSettings));
        
        string IMigrationMetadata.Id
        {
            get { return "201304251518505_Rename_SiteSettings_to_BlogSettings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
