// <auto-generated />
namespace WR.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogSettings_Add_ModerateComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogSettings_Add_ModerateComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201304251623544_BlogSettings_Add_ModerateComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
