// <auto-generated />
namespace WR.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogPostDto_AddCommentCollection : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogPostDto_AddCommentCollection));
        
        string IMigrationMetadata.Id
        {
            get { return "201305021717481_BlogPostDto_AddCommentCollection"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
