// <auto-generated />
namespace WR.Blog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogComment_Add_IpAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogComment_Add_IpAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201305020356147_BlogComment_Add_IpAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
