// <auto-generated />
namespace WR.Blog.Mvc.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class GoogleAccountSiteSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoogleAccountSiteSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "201303311235003_GoogleAccountSiteSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
