// <auto-generated />
namespace WR.Blog.Mvc.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class BlogPageVersions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogPageVersions));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161536281_BlogPageVersions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
